---
- hosts: all
  vars:
    mail_home: /opt/vmail
    mail_user: vmail
    mail_uid: 5000
    db_name: rfc822
    db_user: rfc822
  pre_tasks:
    - name: Fetch/generate passwords
      set_fact:
        password_postgres_dovecot: "{% if ansible_local.passwords is defined %}{{ ansible_local.passwords.postgres.dovecot }}{% else %}{{ 9999999999999999999999 | random | to_uuid }}{% endif %}"
        password_postgres_opendkim: "{% if ansible_local.passwords is defined %}{{ ansible_local.passwords.postgres.opendkim }}{% else %}{{ 9999999999999999999999 | random | to_uuid }}{% endif %}"
        password_postgres_postfix: "{% if ansible_local.passwords is defined %}{{ ansible_local.passwords.postgres.postfix }}{% else %}{{ 9999999999999999999999 | random | to_uuid }}{% endif %}"
        password_postgres_spamd: "{% if ansible_local.passwords is defined %}{{ ansible_local.passwords.postgres.spamd }}{% else %}{{ 9999999999999999999999 | random | to_uuid }}{% endif %}"
    - name: Update apt
      apt:
        cache_valid_time: 3600
        update_cache: yes
    - name: Save passwords
      ini_file:
        dest: /etc/ansible/facts.d/passwords.fact
        mode: 0o600
        owner: root
        group: root
        section: postgres
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - option: dovecot
          value: "{{ password_postgres_dovecot }}"
        - option: opendkim
          value: "{{ password_postgres_opendkim }}"
        - option: postfix
          value: "{{ password_postgres_postfix }}"
        - option: spamd
          value: "{{ password_postgres_spamd }}"
    - name: Create system user for virtual mail
      user:
        name: "{{ mail_user }}"
        uid: "{{ mail_uid }}"
        home: "{{ mail_home }}"
    - name: "Fix permissions on {{ mail_home }}"
      file:
        path: "{{ mail_home }}"
        mode: 0o755
        state: directory
  roles:
    - dehydrated
    - postgres
    - spamassassin
    - postfix
    - dovecot
    - spammilter
    - opendkim
