---
- hosts: all
  vars:
    mail_home: /opt/vmail
    mail_user: vmail
    mail_uid: 5000
    db_name: rfc822
    db_user: rfc822
    db_password: "verysecretpassword"
  pre_tasks:
    - name: Update apt
      apt:
        update_cache: yes
  roles:
    - dehydrated
    - postgres
    - spamassassin
    - postfix
    - dovecot
    - spammilter
