---
- name: Ensure dehydrated and dependencies are installed
  apt:
    state: present
    install_recommends: no
    name:
      - dehydrated
      - nginx-light
      - cron
  notify: accept letsencrypt

- name: Disable default nginx-site
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/default"
  notify: reload nginx

- name: Install nginx-config
  template:
    src: "nginx-dehydrated"
    dest: "/etc/nginx/sites-available/dehydrated"
  notify: reload nginx

- name: Enable nginx-config
  file:
    path: "/etc/nginx/sites-enabled/dehydrated"
    src: "../sites-available/dehydrated"
    state: link
  notify: reload nginx

- name: Create directory for certificate
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  with_items:
     - "/var/lib/dehydrated/certs"
     - "/var/lib/dehydrated/certs/{{ ansible_fqdn }}"

- name: Enable dehydrated cron
  template:
    src: "cron-dehydrated"
    dest: "/etc/cron.d/dehydrated"
  notify: issue certificate
  when: vagrant is undefined

- name: Self-sign a certificate for vagrant tests
  command: "openssl req -subj '/CN={{ ansible_fqdn }}' -x509 -nodes -newkey rsa:2048 -keyout /var/lib/dehydrated/certs/{{ ansible_fqdn }}/privkey.pem -out /var/lib/dehydrated/certs/{{ ansible_fqdn }}/fullchain.pem"
  when: vagrant is defined
